name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.0.0
        with:
          go-version: 1.19
          check-latest: true

      - run: go build ./...
      - run: go test ./...
